create table if not exists employee
(
    id          int primary key generated by default as identity,
    name        varchar,
    designation varchar,
    salary      double precision,
    doj         varchar
);

insert into employee values (1, 'Tom', 'GOOD', 1101, 'sss');
insert into employee values (2, 'Tod', 'GOOD', 32101, 'sss');
insert into employee values (3, 'Bil', 'GOOD', 1101, 'sss');
insert into employee values (4, 'Smit', 'GOOD', 1201, 'sss');
insert into employee values (5, 'Alex', 'GOOD', 111, 'sss');
insert into employee values (6, 'Sir', 'GOOD', 1101, 'sss');
insert into employee values (7, 'Jeri', 'GOOD', 101, 'sss');
insert into employee values (8, 'Sara', 'GOOD', 31, 'sss');
insert into employee values (9, 'Mark', 'GOOD', 311, 'sss');
insert into employee values (10, 'Kain', 'GOOD', 31, 'sss');

truncate employee;
select *
from employee;